In [1]:
import numpy as np

In [2]:
import sys
sys.path.append("../src/common")
import util

In [3]:
c = np.array([[1, 0, 0, 0, 0, 0, 0]])
W = np.random.randn(7, 3)
h = np.dot(c, W)
print(W)
print(h)

[[-1.234046   -1.531353   -0.28888754]
 [ 0.57176081  0.81412415  0.30695904]
 [-1.15312566  2.18649814 -1.25808525]
 [-0.20911352 -0.01300612  0.07310261]
 [ 0.81713631 -0.69400168 -0.78706464]
 [-0.13414606 -0.58572206 -0.63805867]
 [ 0.07454884 -1.1056829  -0.87621846]]
[[-1.234046   -1.531353   -0.28888754]]


In [4]:
text = 'You say goodbye and I say hello.'
corpus, word_to_id, id_to_word = util.preprocess(text)
contexts, target = util.create_contexts_target(corpus, window_size=1)
print(contexts)
print(target)

vocab_size = len(word_to_id)

contexts = util.convert_one_hot(contexts, vocab_size)
target = util.convert_one_hot(target, vocab_size)
print(contexts)
print(target)

[[0 2]
 [1 3]
 [2 4]
 [3 1]
 [4 5]
 [1 6]]
[1 2 3 4 1 5]
[[[1 0 0 0 0 0 0]
  [0 0 1 0 0 0 0]]

 [[0 1 0 0 0 0 0]
  [0 0 0 1 0 0 0]]

 [[0 0 1 0 0 0 0]
  [0 0 0 0 1 0 0]]

 [[0 0 0 1 0 0 0]
  [0 1 0 0 0 0 0]]

 [[0 0 0 0 1 0 0]
  [0 0 0 0 0 1 0]]

 [[0 1 0 0 0 0 0]
  [0 0 0 0 0 0 1]]]
[[0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0]]
