In [5]:
import numpy as np
import sys
sys.path.append("../src/")
import common.util
from common.layers import MatMul

In [14]:
c0 = np.array([[1,0,0,0,0,0,0]])
c1 = np.array([[0,0,1,0,0,0,0]])

W_in = np.random.randn(7, 3)
W_out = np.random.randn(3, 7)

in_layer0 = MatMul(W_in)
in_layer1 = MatMul(W_in)
out_layer = MatMul(W_out)

h0 = in_layer0.forward(c0)
h1 = in_layer1.forward(c1)
h = 0.5 * (h0 + h1)
s = out_layer.forward(h)

print(s)

[[ 1.92264596 -0.7140084  -0.51264179  1.04367385 -1.27262361  2.37175562
  -1.39732234]]


In [7]:
c = np.array([[1, 0, 0, 0, 0, 0, 0]])
W = np.random.randn(7, 3)
h = np.dot(c, W)
print(W)
print(h)

[[ 1.16324274e+00  7.03509668e-02 -3.64323866e-01]
 [ 2.03322303e-03 -4.06828460e-01 -3.06699225e-01]
 [-2.54665004e+00 -2.24168315e+00  9.49628928e-01]
 [ 2.47048799e-01  2.02794422e+00  1.52206559e+00]
 [-2.15928557e+00 -5.73225038e-02  1.06747586e+00]
 [-9.67920839e-01  1.81260823e+00  6.93693637e-01]
 [-1.18123170e+00 -7.22930826e-01 -9.34881437e-01]]
[[ 1.16324274  0.07035097 -0.36432387]]


In [8]:
text = 'You say goodbye and I say hello.'
corpus, word_to_id, id_to_word = util.preprocess(text)
contexts, target = util.create_contexts_target(corpus, window_size=1)
print(contexts)
print(target)

vocab_size = len(word_to_id)

contexts = util.convert_one_hot(contexts, vocab_size)
target = util.convert_one_hot(target, vocab_size)
print(contexts)
print(target)

[[0 2]
 [1 3]
 [2 4]
 [3 1]
 [4 5]
 [1 6]]
[1 2 3 4 1 5]
[[[1 0 0 0 0 0 0]
  [0 0 1 0 0 0 0]]

 [[0 1 0 0 0 0 0]
  [0 0 0 1 0 0 0]]

 [[0 0 1 0 0 0 0]
  [0 0 0 0 1 0 0]]

 [[0 0 0 1 0 0 0]
  [0 1 0 0 0 0 0]]

 [[0 0 0 0 1 0 0]
  [0 0 0 0 0 1 0]]

 [[0 1 0 0 0 0 0]
  [0 0 0 0 0 0 1]]]
[[0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0]]
