In [21]:
import numpy as np

In [22]:
np.dot(np.array([[1, 2, 3]]), np.array([4, 5, 6]))

array([32])

In [23]:
np.dot(np.array([[2, 3, 4]]), np.array([4, 5, 6]))

array([47])

In [24]:
np.dot(np.array([[1, 2, 3], [2, 3, 4]]), np.array([4, 5, 6])) 

array([32, 47])

In [25]:
np.array([[1, 2, 3], [2, 3, 4]]).shape

(2, 3)

In [26]:
## 3 -> 2のNN
x = np.array([[1, 2, 3]])
w = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([1, 2])
print(np.dot(x, w) + b)

print("##############3")
x = np.array([[1, 2, 3], [2, 3, 4], [3, 4, 5], [4, 5, 6], [5, 6, 7]])
w = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([1, 2])
print(np.dot(x, w) + b)

[[23 30]]
##############3
[[23 30]
 [32 42]
 [41 54]
 [50 66]
 [59 78]]


In [27]:
np.random.randn(3, 2)

array([[-0.67841845,  0.40179873],
       [-1.17306231,  0.29951489],
       [-0.46346501, -0.15450416]])

In [28]:
aaa = []
for layer in [[1, 2], [3, 4], [5, 6]]:
    aaa += layer
print(aaa)


[1, 2, 3, 4, 5, 6]


In [29]:
import sys
sys.path.append("./")
import forward_net

In [30]:
x = np.random.randn(10, 2)
model = forward_net.TwoLayerNet(2, 4, 3)
s = model.predict(x)

In [32]:
print(model.params)
print(s)

[array([[-0.97320524,  0.0922784 , -0.02865354,  0.36199796],
       [ 0.43751234,  1.38509927,  0.35913585,  0.79613073]]), array([0., 0., 0., 0.]), array([[ 0.80914661,  1.18646541,  0.11605333],
       [-0.76499247, -0.41491759, -0.23716748],
       [ 0.23244443, -0.25763472,  0.6423741 ],
       [-0.64609845, -1.68298747, -0.39584834]]), array([0., 0., 0.])]
[[-0.45466187 -1.0279356  -0.01611018]
 [-0.60185293 -1.21598071 -0.05606795]
 [-0.04429113 -0.33033348  0.09856437]
 [ 0.06753977 -0.21579927  0.13708003]
 [-0.55522797 -1.14287359 -0.04687872]
 [ 0.09837793 -0.13101723  0.14164521]
 [-0.36394543 -0.84437763  0.00560361]
 [ 0.65936352  0.72871806  0.28055727]
 [-0.18235547 -0.55890163  0.06014076]
 [ 0.10407411 -0.16797159  0.15218336]]


In [4]:
import numpy as np

y = np.array([[0.1, 0.2, 0.7], [0.2, 0.3, 0.5]])
t = np.array([[0, 0, 1], [0, 1, 0]])
print(y)
print(t)
if y.ndim == 1:
    t = t.reshape(1, t.size)
    y = y.reshape(1, y.size)
    
# 教師データがone-hot-vectorの場合、正解ラベルのインデックスに変換
if t.size == y.size:
    t = t.argmax(axis=1)
         
print(t)

batch_size = y.shape[0]

-np.sum(np.log(y[np.arange(batch_size), t] + 1e-7)) / batch_size

[[0.1 0.2 0.7]
 [0.2 0.3 0.5]]
[[0 0 1]
 [0 1 0]]
[2 1]


0.7803236360371291

In [3]:
import numpy as np

x = np.array([[0.1, 0.2, 0.7], [0.2, 0.3, 0.5]])
np.max(x, axis=1)

array([0.7, 0.5])